AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Oficina Mecânica Lambda base template

Globals:
  Function:
    Timeout: 30
    MemorySize: 256

Resources:
  OficinaMecanicaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: handler.lambda_handler
      Runtime: python3.12
      Events:
        HealthCheck:
          Type: Api
          Properties:
            Path: /health
            Method: get
